name: "Build and Test Solution"
description: "Checks out the repository and does something"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      shell: bash
      run: dotnet restore
    - name: Build
      shell: bash
      run: dotnet build --no-restore
    - name: Test
      shell: bash
      run: dotnet test --no-build --verbosity normal
