# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: "Publish to nuget.org"

on:
  push:
    branches: [ "main", "github-actions" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - uses: ./.github/workflows/build-action
      - name: Create Version
        run: echo "VERSION=$(grep -oPm1 "(?<=<VersionPrefix>)[^<]+" ./Directory.Build.props)" >> $GITHUB_ENV
      - name: Print Version
        run: echo ${{ env.VERSION }}
      - if: ${{startsWith(github.event.ref, 'refs/tags/v')}}
        name: Publish Release NuGet
        run: |
          dotnet pack -c Release /p:Version=${{ env.VERSION }}.${{ github.run_number }} /p:InformationalVersion="${{ env.VERSION }}+${{github.ref_name}}/${{github.sha}}"
          #dotnet nuget push ./bin/Release/*.nupkg --api-key ${{ secrets.NUGET_PUSH }} --source https://api.nuget.org/v3/index.json 
      - if: ${{ !startsWith(github.event.ref, 'refs/tags/v') }}
        name: Publish Prerelease NuGet
        run: |
          dotnet pack -c Debug /p:Version=${{ env.VERSION }}.${{ github.run_number }}-prerelease /p:InformationalVersion="${{ env.VERSION }}+${{github.ref_name}}/${{github.sha}}"
          pwd
          dotnet nuget push ./bin/Debug/*.nupkg --api-key ${{ secrets.HELLO_WORLD }} --source https://api.nuget.org/v3/index.json 